student_record: main.o stud_add.o stud_del.o stud_show.o stud_modify.o stud_save.o stud_exit.o stud_sort.o delete_all.o stud_reverse.o
	cc main.c stud_add.c stud_del.c stud_show.c stud_modify.c stud_save.c stud_exit.c stud_sort.c delete_all.c stud_reverse.c -o student_record
main.o:main.c
	cc -c main.c
stud_add.o:stud_add.c
	cc -c stud_add.c
stud_del.o:stud_del.c
	cc -c stud_del.c
stud_show.o:stud_show.c
	cc -c stud_show.c
stud_modify.o:stud_modify.c
	cc -c stud_modify.c 
stud_save.o:stud_save.c
	cc -c stud_save.c
stud_exit.o:stud_exit.c
	cc -c stud_exit.c
stud_reverse.o:stud_reverse.c
	cc -c stud_reverse.c
stud_sort.o:stud_sort.c
	cc -c stud_sort.c
delete_all.o:delete_all.c
	cc -c delete_all.c
